version: "3.2"
services:
  nginx:
    image: nginx:latest
    ports:
      - "60001:443"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=443
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ../backend:/var/www/html
      - ./log/nginx:/var/log/nginx
      - /root/app/ssl:/ssl
    networks:
      - chatroom
  php:
    build: ./php
    volumes:
      - ../backend:/var/www/html
    networks:
      - chatroom
  composer:
    image: composer:latest
    volumes:
      - ../backend:/app
    command: /bin/bash -c "composer install && vendor/bin/doctrine orm:schema-tool:create"
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: chatroom
      MYSQL_ROOT_PASSWORD: IAMROOT
    volumes:
#      - ./data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    networks:
      - chatroom
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "60002:80"
    restart: always
    depends_on:
      - mysql
    environment:
      - PMA_HOST=mysql
    networks:
      - chatroom
networks:
  chatroom: